'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('kost', [
      {
        kost_id: Sequelize.UUIDV4(),
        nama_kost: 'Kost Indra Pratama',
        alamat: 'Jl. Raya Cilangkap No. 8, Cipinang, Jakarta Timur',
        deskripsi: 'Kost nyaman dan strategis, dekat dengan Universitas Indraprasta PGRI.',
        jenis_kost: 'campur',
        harga: 1200000,
        status: 'tersedia',
        harga_id: 1,
        luas_id: 1,
        fasilitas_id: 1,
        jarak_id: 1,
        keamanan_id: 1,
        photos: [
          'https://example.com/photo1.jpg',
          'https://example.com/photo2.jpg',
          'https://example.com/photo3.jpg',
        ],
        thumb_image: 'https://example.com/photo1.jpg',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        kost_id: Sequelize.UUIDV4(),
        nama_kost: 'Kost PGRI Residence',
        alamat: 'Jl. Raya Pahlawan No. 3, Duren Sawit, Jakarta Timur',
        deskripsi: 'Kost eksklusif di daerah strategis, dekat kampus Universitas Indraprasta PGRI.',
        jenis_kost: 'wanita',
        harga: 1500000,
        status: 'tidak tersedia',
        harga_id: 2,
        luas_id: 2,
        fasilitas_id: 2,
        jarak_id: 2,
        keamanan_id: 2,
        photos: [
          'https://example.com/photo1.jpg',
          'https://example.com/photo2.jpg',
        ],
        thumb_image: 'https://example.com/photo1.jpg',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        kost_id: Sequelize.UUIDV4(),
        nama_kost: 'Kost Griya Indraprasta',
        alamat: 'Jl. Indraprasta No. 5, Cipayung, Jakarta Timur',
        deskripsi: 'Kost nyaman dengan fasilitas lengkap dan harga terjangkau, sangat dekat dengan kampus.',
        jenis_kost: 'pria',
        harga: 1000000,
        status: 'tersedia',
        harga_id: 3,
        luas_id: 3,
        fasilitas_id: 3,
        jarak_id: 3,
        keamanan_id: 3,
        photos: [
          'https://example.com/photo1.jpg',
          'https://example.com/photo2.jpg',
        ],
        thumb_image: 'https://example.com/photo1.jpg',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        kost_id: Sequelize.UUIDV4(),
        nama_kost: 'Kost Amani',
        alamat: 'Jl. H. Sanusi No. 10, Kampung Melayu, Jakarta Timur',
        deskripsi: 'Kost dengan suasana tenang dan dekat dengan Universitas Indraprasta PGRI.',
        jenis_kost: 'campur',
        harga: 1300000,
        status: 'tersedia',
        harga_id: 4,
        luas_id: 4,
        fasilitas_id: 4,
        jarak_id: 4,
        keamanan_id: 4,
        photos: [
          'https://example.com/photo1.jpg',
          'https://example.com/photo2.jpg',
        ],
        thumb_image: 'https://example.com/photo1.jpg',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        kost_id: Sequelize.UUIDV4(),
        nama_kost: 'Kost Elok',
        alamat: 'Jl. Jatinegara No. 2, Jatinegara, Jakarta Timur',
        deskripsi: 'Kost dengan fasilitas lengkap dan lokasi strategis dekat kampus.',
        jenis_kost: 'wanita',
        harga: 1400000,
        status: 'tidak tersedia',
        harga_id: 5,
        luas_id: 5,
        fasilitas_id: 5,
        jarak_id: 5,
        keamanan_id: 5,
        photos: [
          'https://example.com/photo1.jpg',
          'https://example.com/photo2.jpg',
        ],
        thumb_image: 'https://example.com/photo1.jpg',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        kost_id: Sequelize.UUIDV4(),
        nama_kost: 'Kost Alam Indah',
        alamat: 'Jl. Cipinang Cempedak No. 7, Cipinang, Jakarta Timur',
        deskripsi: 'Kost dengan lingkungan yang asri dan harga yang terjangkau, dekat dengan kampus.',
        jenis_kost: 'campur',
        harga: 1250000,
        status: 'tersedia',
        harga_id: 1,
        luas_id: 1,
        fasilitas_id: 1,
        jarak_id: 1,
        keamanan_id: 1,
        photos: [
          'https://example.com/photo1.jpg',
          'https://example.com/photo2.jpg',
        ],
        thumb_image: 'https://example.com/photo1.jpg',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        kost_id: Sequelize.UUIDV4(),
        nama_kost: 'Kost Taman Indraprasta',
        alamat: 'Jl. Raya Kalimalang No. 14, Jakarta Timur',
        deskripsi: 'Kost dengan fasilitas parkir luas, cocok untuk mahasiswa dan pekerja.',
        jenis_kost: 'pria',
        harga: 950000,
        status: 'tersedia',
        harga_id: 2,
        luas_id: 2,
        fasilitas_id: 2,
        jarak_id: 2,
        keamanan_id: 2,
        photos: [
          'https://example.com/photo1.jpg',
          'https://example.com/photo2.jpg',
        ],
        thumb_image: 'https://example.com/photo1.jpg',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        kost_id: Sequelize.UUIDV4(),
        nama_kost: 'Kost Mitra Indraprasta',
        alamat: 'Jl. Mitra No. 9, Duren Sawit, Jakarta Timur',
        deskripsi: 'Kost dengan lokasi strategis dekat dengan kampus dan akses transportasi umum.',
        jenis_kost: 'wanita',
        harga: 1150000,
        status: 'tidak tersedia',
        harga_id: 3,
        luas_id: 3,
        fasilitas_id: 3,
        jarak_id: 3,
        keamanan_id: 3,
        photos: [
          'https://example.com/photo1.jpg',
          'https://example.com/photo2.jpg',
        ],
        thumb_image: 'https://example.com/photo1.jpg',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        kost_id: Sequelize.UUIDV4(),
        nama_kost: 'Kost Hijau',
        alamat: 'Jl. Raya Bekasi Timur No. 4, Jakarta Timur',
        deskripsi: 'Kost dengan lingkungan yang nyaman dan aman, dekat dengan Universitas Indraprasta PGRI.',
        jenis_kost: 'pria',
        harga: 1050000,
        status: 'tersedia',
        harga_id: 4,
        luas_id: 4,
        fasilitas_id: 4,
        jarak_id: 4,
        keamanan_id: 4,
        photos: [
          'https://example.com/photo1.jpg',
          'https://example.com/photo2.jpg',
        ],
        thumb_image: 'https://example.com/photo1.jpg',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('kost', null, {});
  },
};
